### ISSUE TITLE
[FEATURE] Socket Connection

### ISSUE THREAD

**Issue by kqnade** [kqnade/CHaserLua-archive#1]
### Checkboxes

- [X] I have searched the [issues](https://github.com/kqnade/CHaserLua/issues) of this repository and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://github.com/kqnade/CHaserLua/readme.md) and believe that my request is not covered.

### Describe the request

```shell
A connection function is essential to execute based on this code.
```

### Describe the solution you would like

```shell
. Define functions for connection in /connect.lua
```

### Describe alternatives you have considered

```shell
none
```

### Additional context

```shell
none
```

**Comment by kqnade** [comment]
## Tasks
- [x] Send Name (Initialize)
- [ ] Send Get_Ready
- [ ] Send Move (4 direction)
  - [ ] Move (Up)
  - [ ] Move (Down)
  - [ ] Move Left
  - [ ] Move Right
- [ ] Send Look
  - [ ] Look (Up)
  - [ ] Look (Down)
  - [ ] Look (Left)
  - [ ] Look (Right)
- [ ] Send Search
  - [ ] Search (Up)
  - [ ] Search (Down)
  - [ ] Search (Left)
  - [ ] Search (Right)
- [ ] Send Put
  - [ ] Put (Up)
  - [ ] Put (Down)
  - [ ] Put (Left)
  - [ ] Put (Right)
