### ISSUE TITLE
Write PR Template

### ISSUE THREAD

**Issue by kqnade** [kqnade/CHaserLua-archive#25]
## Tasks
- [ ] Make .github/PULL_REQUEST_TEMPLATE/
- [ ] make PR template
  - [ ] For Marge to dev
  - [ ] For marge to main (release)
